---
title: "Map of West Africa Countries"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
date: "2022-12-04"
---


Web page using R Markdown that features a map created with Leaflet by Six_Paths 

This Webpage hosted on GitHub Pages.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Product _ Leaft Map

#####
```{r, eval=TRUE, echo=FALSE}
library("leaflet")
```

##### Build data with require values
```{r, eval=TRUE}
west_Africa_Countries = data.frame(names = c("Nigeria", "GHANA", "IVORY COAST",
                                             "NIGER", "Burkina Faso", "Mali",
                                             "Senegal", "Guinea", "BENIN",
                                             "Togo", "Sierra Leone", "Liberia",
                                             "Mauritania",  "Gambia",
                                             "Guinea-Bissau", "Cabo Verde"),
                                   pop = c(206139589, 31072940, 26378274,
                                           24206644, 20903273, 20250833,
                                           16743927, 13132795, 12123200, 
                                           8278724, 7976983,	5057681, 4649658,
                                           2416668, 1968001, 555987),
                                   longitude = c(8.675277, -1.023194, -5.54708, 8.081666,
                                            -1.561593, -3.996166, -14.452362, -9.696645,
                                            2.315834,  0.824782, -11.779889, -9.429499,
                                            -10.940835, -15.310139, -15.180413,
                                            -23.0418),
                                   latitude = c(9.081999, 7.946527, 7.539989, 17.607789, 
                                           12.238333, 17.570692, 14.497401, 9.945587, 
                                           9.30769, 8.619543, 8.460555, 6.428055,
                                           21.00789, 13.443182, 11.803749, 16.5388))
```


##### Build Map
```{r, eval=TRUE}
west_Africa_Countries %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(weight=1, radius=sqrt(west_Africa_Countries$pop)*30) %>%
  addMarkers(lat=west_Africa_Countries$latitude, lng=west_Africa_Countries$longitude, 
           popup=west_Africa_Countries$pop)
```



